-- Criação da database
CREATE database teste;
USE teste;
-- Encoding UTF-8
SET NAMES 'utf8mb4';

-- Querry para o arquivo CSV (Relatorio_cadop.csv)
CREATE TABLE cadastro_operadoras (
    REGISTRO_ANS INT NOT NULL,
    CNPJ CHAR(14) NOT NULL,
    RAZAO_SOCIAL VARCHAR(255) NOT NULL,
    NOME_FANTASIA VARCHAR(255),
    MODALIDADE VARCHAR(100),
    LOGRADOURO VARCHAR(255),
    NUMERO VARCHAR(20),
    COMPLEMENTO VARCHAR(100),
    BAIRRO VARCHAR(100),
    CIDADE VARCHAR(100),
    UF CHAR(2),
    CEP CHAR(8),
    DDD CHAR(2),
    TELEFONE VARCHAR(15),
    FAX VARCHAR(15),
    ENDERECO_ELETRONICO VARCHAR(255),
    REPRESENTANTE VARCHAR(255),
    CARGO_REPRESENTANTE VARCHAR(100),
    REGIAO_DE_COMERCIALIZACAO VARCHAR(100),
    DATA_REGISTRO_ANS DATE,
    PRIMARY KEY (REGISTRO_ANS)
);

-- Querry para os registros anuais dos dois últimos anos (2023 e 2024)
CREATE TABLE contas_financeiras (
    DATA				DATE,
    REG_ANS 			VARCHAR(20),
    CD_CONTA_CONTABIL 	VARCHAR(50),
    DESCRICAO 			TEXT,
    VL_SALDO_INICIAL 	DECIMAL(10,2),
    VL_SALDO_FINAL 		DECIMAL(10,2),
    PRIMARY KEY (DATA, REG_ANS, CD_CONTA_CONTABIL)
);
